from pathlib import Path


ROOT = Path(__file__).resolve().parent
source = (ROOT / "index.html").read_text(encoding="utf-8")

translations = {
    "PA3 Paper Prototypes — Group 10": "Prototype giấy PA3 — Nhóm 10",
    "2 scenarios": "2 kịch bản",
    "6 alternatives": "6 phương án",
    "one PA3 decision": "một quyết định cho PA3",
    "GROUP 10 · CSC13112 · UI/UX DESIGN · PA3": "NHÓM 10 · CSC13112 · THIẾT KẾ UI/UX · PA3",
    "Paper": "Prototype giấy",
    "prototypes": "tương tác",
    "FIFA.com ticket confidence + Chess.com beginner review. Six lo-fi interaction models carried forward from PA1 → PA2 for formative testing.": "Sự an tâm khi quản lý vé trên FIFA.com + review ván cờ cho người mới trên Chess.com. Sáu mô hình tương tác lo-fi được phát triển tiếp từ PA1 → PA2 để kiểm thử formative.",
    "Scenario 01 · FIFA.com": "Kịch bản 01 · FIFA.com",
    "Scenario 02 · Chess.com": "Kịch bản 02 · Chess.com",
    "PA3 · 2026": "PA3 · 2026",
    "PA3 DESIGN SPACE": "KHÔNG GIAN THIẾT KẾ PA3",
    "Six hypotheses.": "Sáu giả thuyết.",
    "Two jobs to be done.": "Hai mục tiêu cần hoàn thành.",
    "These are parallel alternatives for formative testing — not six final features intended to coexist.": "Đây là các phương án song song để kiểm thử formative — không phải sáu tính năng cuối cùng cùng tồn tại.",
    "FIFA · Alt 1": "FIFA · PA 1",
    "Status": "Trạng thái",
    "What is my ticket status now?": "Trạng thái vé của tôi hiện tại là gì?",
    "FIFA · Alt 2": "FIFA · PA 2",
    "Progress": "Tiến trình",
    "Where am I in the process?": "Tôi đang ở đâu trong quy trình?",
    "FIFA · Alt 3": "FIFA · PA 3",
    "Actions": "Thao tác",
    "What can I do right now?": "Tôi có thể làm gì ngay bây giờ?",
    "Chess · Alt 1": "Chess · PA 1",
    "Guided sequence": "Chuỗi có hướng dẫn",
    "Show me one useful step at a time.": "Hãy chỉ cho tôi từng bước hữu ích.",
    "Chess · Alt 2": "Chess · PA 2",
    "Self-selected cards": "Thẻ tự chọn",
    "Let me choose the moment to review.": "Cho tôi chọn khoảnh khắc muốn review.",
    "Chess · Alt 3": "Chess · PA 3",
    "Conversation": "Hội thoại",
    "Let me ask beside the board.": "Cho tôi hỏi ngay cạnh bàn cờ.",
    "01 · FIFA.com": "01 · FIFA.com",
    "baseline evidence": "bằng chứng nền",
    "SCENARIO 01 · ORIGINAL INTERFACE": "KỊCH BẢN 01 · GIAO DIỆN GỐC",
    "Ticket entry is": "Điểm bắt đầu của vé là",
    "tournament-first.": "ưu tiên giải đấu.",
    "PA2 capture · tournament cards, register-interest and buy-now entry points": "Ảnh chụp PA2 · thẻ giải đấu, điểm vào đăng ký quan tâm và mua ngay",
    "What the capture supports": "Ảnh chụp cho thấy",
    "The page organizes discovery around tournament logos and ticket / hospitality cards. Users choose an event card before they can reason about a ticket state.": "Trang tổ chức việc khám phá quanh logo giải đấu và các thẻ vé / hospitality. Người dùng phải chọn một thẻ sự kiện trước khi có thể suy luận về trạng thái vé.",
    "What is not visible here": "Điều chưa thấy ở đây",
    "No consolidated cross-tournament status dashboard, persistent ticket timeline, or account-level next-step overview appears in this captured state.": "Trong trạng thái được chụp này chưa có dashboard trạng thái tổng hợp nhiều giải đấu, timeline vé liên tục, hay tổng quan bước tiếp theo ở cấp tài khoản.",
    "PA2 finding carried forward": "Phát hiện PA2 được mang sang",
    "FIFA ticket action lacks consolidated decision confidence; outbound routes need trust context.": "Thao tác vé trên FIFA thiếu sự an tâm khi ra quyết định; các luồng chuyển ra ngoài cần có ngữ cảnh tin cậy.",
    "SOURCE · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png · FIGURE F2-E09": "NGUỒN · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png · HÌNH F2-E09",
    "FIFA baseline": "FIFA · nền",
    "01 · FIFA.com / ALT 1": "01 · FIFA.com / PA 1",
    "status dashboard": "dashboard trạng thái",
    "FIFA ALTERNATIVE 01": "FIFA · PHƯƠNG ÁN 01",
    "Status first.": "Trạng thái trước.",
    "Confidence first.": "An tâm trước.",
    "Approved artifact · alt1scenario1.png": "Artifact đã duyệt · alt1scenario1.png",
    "state recognition": "nhận diện trạng thái",
    "confidence": "sự an tâm",
    "Problem": "Vấn đề",
    "A user must quickly know whether tickets are valid, pending, cancelled, or waiting on them.": "Người dùng phải nhanh chóng biết vé hợp lệ, đang chờ, đã hủy hay đang chờ chính họ xử lý.",
    "Interaction model": "Mô hình tương tác",
    "An account-level overview: status counts → upcoming event cards → primary action → help and notifications.": "Tổng quan ở cấp tài khoản: số lượng theo trạng thái → thẻ sự kiện sắp tới → thao tác chính → trợ giúp và thông báo.",
    "Delta from original": "Khác biệt so với bản gốc",
    "Replaces tournament-first discovery with a persistent, multi-event status surface while retaining FIFA navigation and official context.": "Thay việc khám phá ưu tiên giải đấu bằng một bề mặt trạng thái lâu dài cho nhiều sự kiện, đồng thời giữ navigation và ngữ cảnh chính thức của FIFA.",
    "Testable hypothesis": "Giả thuyết có thể kiểm thử",
    "Users can identify the current ticket state and the safest next action without opening several event pages.": "Người dùng có thể xác định trạng thái vé hiện tại và thao tác tiếp theo an toàn nhất mà không cần mở nhiều trang sự kiện.",
    "PROTOTYPE · alt1scenario1.png · COMPARISON · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png": "PROTOTYPE · alt1scenario1.png · SO SÁNH · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png",
    "FIFA · status dashboard": "FIFA · dashboard trạng thái",
    "interaction anatomy": "giải phẫu tương tác",
    "THE STATUS DASHBOARD IN DETAIL": "CHI TIẾT DASHBOARD TRẠNG THÁI",
    "A fast read of": "Đọc nhanh",
    "what is true now.": "điều đang đúng lúc này.",
    "01 · four-state summary": "01 · tóm tắt bốn trạng thái",
    "02 · upcoming events + primary action": "02 · sự kiện sắp tới + thao tác chính",
    "03 · support + freshness": "03 · trợ giúp + độ mới",
    "04 · original: choose a tournament first": "04 · bản gốc: chọn giải đấu trước",
    "Strength": "Điểm mạnh",
    "High discoverability for state recognition; counts, validity copy, and event cards make the overview scannable.": "Khả năng nhận diện trạng thái cao; số lượng, nội dung về hiệu lực và thẻ sự kiện giúp quét tổng quan nhanh.",
    "Weakness": "Điểm yếu",
    "“Pending” can still be ambiguous if ownership, expected resolution, or the difference between “View Order” and “View Tickets” is unclear.": "“Đang chờ” vẫn có thể mơ hồ nếu chưa rõ ai chịu trách nhiệm, thời gian xử lý dự kiến, hoặc khác biệt giữa “View Order” và “View Tickets”.",
    "Formative-testing hypothesis": "Giả thuyết kiểm thử formative",
    "Ask users to explain one confirmed and one pending event in their own words, then choose the next action. Record wrong paths and hesitation.": "Yêu cầu người dùng diễn giải một sự kiện đã xác nhận và một sự kiện đang chờ bằng lời của họ, rồi chọn thao tác tiếp theo. Ghi lại đường đi sai và thời điểm do dự.",
    "Traceability": "Truy xuất",
    "FIFA · anatomy": "FIFA · giải phẫu",
    "05 / 20": "05 / 20",
    "01 · FIFA.com / ALT 2": "01 · FIFA.com / PA 2",
    "timeline tracker": "tracker timeline",
    "FIFA ALTERNATIVE 02": "FIFA · PHƯƠNG ÁN 02",
    "Progress first.": "Tiến trình trước.",
    "Freshness first.": "Độ mới trước.",
    "Approved artifact · alt2scenario1.png": "Artifact đã duyệt · alt2scenario1.png",
    "lifecycle": "vòng đời",
    "official source": "nguồn chính thức",
    "freshness": "độ mới",
    "Status labels alone do not explain where an order is, who owns the next step, or whether the information is current.": "Nhãn trạng thái đơn lẻ không giải thích đơn hàng đang ở đâu, ai phụ trách bước tiếp theo, hay thông tin còn cập nhật không.",
    "A progress-first surface: lifecycle milestones → current step → update history → official next steps.": "Bề mặt ưu tiên tiến trình: các mốc vòng đời → bước hiện tại → lịch sử cập nhật → bước tiếp theo chính thức.",
    "Adds an explicit order lifecycle and provenance signals to a page that is otherwise organized around tournament entry.": "Bổ sung vòng đời đơn hàng rõ ràng và tín hiệu nguồn gốc cho một trang vốn tổ chức quanh điểm vào giải đấu.",
    "Users can point to the current milestone, say what happens next, and judge whether the update is official and fresh.": "Người dùng có thể chỉ ra mốc hiện tại, nói điều gì xảy ra tiếp theo, và đánh giá cập nhật có chính thức và mới hay không.",
    "PROTOTYPE · alt2scenario1.png · COMPARISON · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png": "PROTOTYPE · alt2scenario1.png · SO SÁNH · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png",
    "FIFA · timeline tracker": "FIFA · tracker timeline",
    "06 / 20": "06 / 20",
    "THE TIMELINE TRACKER IN DETAIL": "CHI TIẾT TRACKER TIMELINE",
    "From “what is my status?” to": "Từ “trạng thái của tôi là gì?” đến",
    "“where am I?”": "“tôi đang ở đâu?”",
    "01 · completed / current / upcoming": "01 · đã xong / hiện tại / sắp tới",
    "02 · freshness + update history": "02 · độ mới + lịch sử cập nhật",
    "03 · official next steps": "03 · bước tiếp theo chính thức",
    "04 · pending order position": "04 · vị trí đơn hàng đang chờ",
    "Progress visibility gives normal waiting a shape. The “last updated” and official-source labels support calibrated trust.": "Việc nhìn thấy tiến trình giúp khoảng thời gian chờ bình thường có hình dạng. Nhãn “cập nhật lần cuối” và nguồn chính thức hỗ trợ niềm tin có cơ sở.",
    "Future gray milestones may look like tasks. Ownership and normal duration need to be explicit.": "Các mốc màu xám trong tương lai có thể trông như nhiệm vụ. Cần nói rõ ai phụ trách và thời lượng thông thường.",
    "Ask users to locate the current stage, explain what is pending, and identify the next user-owned action without treating every milestone as an assignment.": "Yêu cầu người dùng tìm giai đoạn hiện tại, giải thích điều đang chờ, và xác định thao tác tiếp theo thuộc về họ mà không xem mọi mốc là một nhiệm vụ.",
    "Fundamental difference": "Khác biệt nền tảng",
    "current status": "trạng thái hiện tại",
    "process position": "vị trí trong quy trình",
    "SOURCE · PA2/evidence-index.csv · F2-E09 · hypothesis boundary: no observed participant outcome": "NGUỒN · PA2/evidence-index.csv · F2-E09 · ranh giới giả thuyết: chưa quan sát kết quả người tham gia",
    "07 / 20": "07 / 20",
    "01 · FIFA.com / ALT 3": "01 · FIFA.com / PA 3",
    "action hub": "hub thao tác",
    "FIFA ALTERNATIVE 03": "FIFA · PHƯƠNG ÁN 03",
    "Tasks first.": "Nhiệm vụ trước.",
    "Shortcuts first.": "Lối tắt trước.",
    "Approved artifact · alt3scenario1.png": "Artifact đã duyệt · alt3scenario1.png",
    "shortcuts": "lối tắt",
    "handoff": "chuyển giao",
    "official options": "tùy chọn chính thức",
    "Common post-purchase actions are hard to find when entry pages are built around browsing instead of doing.": "Các thao tác thường dùng sau mua khó tìm khi trang vào được xây quanh việc xem thay vì làm.",
    "A task-first hub: ticket actions → calendar / itinerary / venue support → official options → provider boundary.": "Một hub ưu tiên nhiệm vụ: thao tác vé → lịch / hành trình / hỗ trợ địa điểm → tùy chọn chính thức → ranh giới nhà cung cấp.",
    "Reorders the surface around action execution and adds a visible “before you leave FIFA.com” handoff cue.": "Sắp xếp lại bề mặt quanh việc thực hiện thao tác và thêm tín hiệu chuyển giao rõ ràng “trước khi rời FIFA.com”.",
    "Users find a common ticket action quickly and can tell whether an option is core ticket management or an external add-on.": "Người dùng tìm nhanh một thao tác vé phổ biến và phân biệt được tùy chọn đó là quản lý vé cốt lõi hay tiện ích bên ngoài.",
    "PROTOTYPE · alt3scenario1.png · COMPARISON · PA2/capture-work/fifa/desktop/fifa-32-before-partner-handoff.png": "PROTOTYPE · alt3scenario1.png · SO SÁNH · PA2/capture-work/fifa/desktop/fifa-32-before-partner-handoff.png",
    "FIFA · action hub": "FIFA · hub thao tác",
    "08 / 20": "08 / 20",
    "THE ACTION HUB IN DETAIL": "CHI TIẾT HUB THAO TÁC",
    "The question becomes": "Câu hỏi trở thành",
    "“what can I do?”": "“tôi có thể làm gì?”",
    "01 · high-frequency shortcuts": "01 · lối tắt dùng thường xuyên",
    "02 · official options": "02 · tùy chọn chính thức",
    "03 · handoff trust banner": "03 · banner tin cậy khi chuyển giao",
    "04 · support + security": "04 · trợ giúp + bảo mật",
    "Recognition over recall: large labeled shortcuts make routine actions visible without hunting through navigation.": "Ưu tiên nhận diện thay vì nhớ lại: các lối tắt có nhãn lớn làm thao tác thường ngày hiện rõ mà không phải tìm trong navigation.",
    "Equal-weight actions and optional commercial options can create a new choice problem or make extras look required.": "Các thao tác có trọng số ngang nhau và tùy chọn thương mại có thể tạo vấn đề lựa chọn mới, hoặc khiến phần bổ sung trông như bắt buộc.",
    "Give users a “transfer tickets” and an “official options” task. Observe first action, category errors, and whether they can explain the partner boundary.": "Giao cho người dùng nhiệm vụ “chuyển vé” và “tùy chọn chính thức”. Quan sát thao tác đầu tiên, lỗi phân loại, và khả năng giải thích ranh giới đối tác.",
    "process understanding": "hiểu quy trình",
    "task execution": "thực hiện nhiệm vụ",
    "SOURCE · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png + fifa-32-before-partner-handoff.png": "NGUỒN · PA2/capture-work/fifa/desktop/fifa-20-tickets-hospitality-landing.png + fifa-32-before-partner-handoff.png",
    "09 / 20": "09 / 20",
    "alternative comparison": "so sánh phương án",
    "SCENARIO 01 · COMPARISON": "KỊCH BẢN 01 · SO SÁNH",
    "Same ticket job.": "Cùng một mục tiêu về vé.",
    "Different mental model.": "Khác mô hình tư duy.",
    "Dimension": "Chiều đánh giá",
    "Original FIFA": "FIFA gốc",
    "Alt 1 · Status": "PA 1 · Trạng thái",
    "Alt 2 · Timeline": "PA 2 · Timeline",
    "Alt 3 · Actions": "PA 3 · Thao tác",
    "Primary user question": "Câu hỏi chính của người dùng",
    "Which tournament card should I open?": "Tôi nên mở thẻ giải đấu nào?",
    "What is my status now?": "Trạng thái hiện tại của tôi là gì?",
    "Information architecture": "Kiến trúc thông tin",
    "Tournament cards, ticket / hospitality entry": "Thẻ giải đấu, điểm vào vé / hospitality",
    "State summary + event cards": "Tóm tắt trạng thái + thẻ sự kiện",
    "Order milestones + updates": "Mốc đơn hàng + cập nhật",
    "Quick actions + official options": "Thao tác nhanh + tùy chọn chính thức",
    "Main benefit": "Lợi ích chính",
    "Clear event discovery": "Khám phá sự kiện rõ ràng",
    "Fast confidence check": "Kiểm tra sự an tâm nhanh",
    "Progress and freshness": "Tiến trình và độ mới",
    "Low-friction task execution": "Thực hiện nhiệm vụ ít ma sát",
    "Main risk": "Rủi ro chính",
    "Context is scattered after entry": "Ngữ cảnh bị phân tán sau khi vào",
    "Pending state may be non-diagnostic": "Trạng thái chờ có thể không đủ chẩn đoán",
    "Future steps may look user-owned": "Bước tương lai có thể trông như việc của người dùng",
    "Choice overload / optional extras": "Quá nhiều lựa chọn / phần bổ sung tùy chọn",
    "Best-fit task": "Nhiệm vụ phù hợp nhất",
    "Discover an event": "Khám phá một sự kiện",
    "Triage ticket state": "Phân loại trạng thái vé",
    "Understand waiting and next steps": "Hiểu việc chờ và bước tiếp theo",
    "Transfer, calendar, venue, support": "Chuyển vé, lịch, địa điểm, trợ giúp",
    "Formative focus": "Trọng tâm formative",
    "Entry recognition": "Nhận diện điểm vào",
    "State comprehension": "Hiểu trạng thái",
    "Ownership + freshness": "Trách nhiệm + độ mới",
    "First action + handoff trust": "Thao tác đầu tiên + tin cậy khi chuyển giao",
    "Decision rule:": "Quy tắc quyết định:",
    "do not declare a winner before real novice participants complete the same scenario tasks across all three alternatives.": "không chọn phương án thắng trước khi người mới thật sự hoàn thành cùng nhiệm vụ kịch bản ở cả ba phương án.",
    "SOURCE · PA2/evidence-index.csv · F2-E09 · F2-E11 · F2-E12 · PA2/traceability-matrix.csv": "NGUỒN · PA2/evidence-index.csv · F2-E09 · F2-E11 · F2-E12 · PA2/traceability-matrix.csv",
    "FIFA · comparison": "FIFA · so sánh",
    "10 / 20": "10 / 20",
    "02 · CHESS.COM": "02 · CHESS.COM",
    "SCENARIO 02 · ORIGINAL INTERFACE": "KỊCH BẢN 02 · GIAO DIỆN GỐC",
    "Analysis starts with": "Analysis bắt đầu với",
    "many choices.": "quá nhiều lựa chọn.",
    "PA2 capture · setup, explore, search, collections, import and start analysis": "Ảnh chụp PA2 · thiết lập, khám phá, tìm kiếm, bộ sưu tập, import và bắt đầu analysis",
    "The Analysis entry presents several paths beside a board: Set Up Position, Explore, Game Search, Game Collections, upload / import, and Start Analysis.": "Điểm vào Analysis đưa ra nhiều đường đi cạnh bàn cờ: Set Up Position, Explore, Game Search, Game Collections, upload / import và Start Analysis.",
    "Why this matters for beginners": "Vì sao điều này quan trọng với người mới",
    "A novice must decide where to begin before they know which path corresponds to “understand my last game.” That is a recall-heavy entry.": "Người mới phải quyết định bắt đầu ở đâu trước khi biết đường đi nào tương ứng với “hiểu ván cờ vừa chơi”. Đây là một điểm vào đòi hỏi nhớ lại nhiều.",
    "Bridge pattern in PA2": "Mẫu cầu nối trong PA2",
    "Learn-to-Play uses a simpler progressive path with an explanatory prompt and Next Lesson action. The three alternatives test different ways to bring that guidance into review.": "Learn-to-Play dùng một đường đi tiến dần đơn giản hơn với prompt giải thích và thao tác Next Lesson. Ba phương án kiểm thử các cách khác nhau để đưa hướng dẫn đó vào review.",
    "SOURCE · PA2/capture-work/chess/desktop/chess-29-analysis-board.png · FIGURE C2-E10 · SUPPORTING C2-E08": "NGUỒN · PA2/capture-work/chess/desktop/chess-29-analysis-board.png · HÌNH C2-E10 · HỖ TRỢ C2-E08",
    "Chess baseline": "Chess · nền",
    "11 / 20": "11 / 20",
    "02 · CHESS.COM / ALT 1": "02 · CHESS.COM / PA 1",
    "beginner review flow": "luồng review cho người mới",
    "CHESS ALTERNATIVE 01": "CHESS · PHƯƠNG ÁN 01",
    "One mistake.": "Một lỗi.",
    "One useful next step.": "Một bước tiếp theo hữu ích.",
    "Approved artifact · alt1scenario2.png": "Artifact đã duyệt · alt1scenario2.png",
    "guided": "có hướng dẫn",
    "plain language": "ngôn ngữ dễ hiểu",
    "practice bridge": "cầu nối luyện tập",
    "Beginners can see a board but not know which mistake matters or how to turn an explanation into practice.": "Người mới có thể nhìn thấy bàn cờ nhưng không biết lỗi nào quan trọng hay biến lời giải thích thành luyện tập thế nào.",
    "A fixed sequence: Beginner Review → mistake → explanation → better move → Try this move → practice.": "Một chuỗi cố định: Beginner Review → lỗi → giải thích → nước đi tốt hơn → Try this move → luyện tập.",
    "Collapses the multi-path Analysis entry into a guided mode that borrows the Learn page’s progressive next-step pattern.": "Thu gọn điểm vào Analysis nhiều đường đi thành một chế độ có hướng dẫn, mượn mẫu bước tiếp theo tiến dần của trang Learn.",
    "Beginners can explain one mistake, identify the better move, and reach relevant practice with low decision burden.": "Người mới có thể giải thích một lỗi, xác định nước đi tốt hơn và đến bài luyện tập phù hợp với gánh nặng quyết định thấp.",
    "PROTOTYPE · alt1scenario2.png · COMPARISON · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png": "PROTOTYPE · alt1scenario2.png · SO SÁNH · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png",
    "Chess · beginner review flow": "Chess · luồng review cho người mới",
    "12 / 20": "12 / 20",
    "THE BEGINNER REVIEW FLOW IN DETAIL": "CHI TIẾT LUỒNG REVIEW CHO NGƯỜI MỚI",
    "The system controls the": "Hệ thống kiểm soát",
    "review order.": "thứ tự review.",
    "01 · step 2 of 3": "01 · bước 2 trên 3",
    "02 · plain-language mistake": "02 · lỗi bằng ngôn ngữ dễ hiểu",
    "03 · better move + practice": "03 · nước đi tốt hơn + luyện tập",
    "04 · original pattern: next lesson": "04 · mẫu gốc: bài học tiếp theo",
    "Low memory load: progress, explanation, better move, and practice are placed in one focused path.": "Tải nhớ thấp: tiến trình, giải thích, nước đi tốt hơn và luyện tập nằm trong một đường đi tập trung.",
    "Experienced users may find the fixed order slow or restrictive; beginners may still need piece names and visual arrows before notation.": "Người có kinh nghiệm có thể thấy thứ tự cố định chậm hoặc hạn chế; người mới vẫn có thể cần tên quân và mũi tên trực quan trước ký hiệu.",
    "Measure whether a novice can describe the mistake without repeating the label, try the better move, and say what they would do next.": "Đo xem người mới có thể mô tả lỗi mà không lặp lại nhãn, thử nước đi tốt hơn và nói bước tiếp theo họ sẽ làm gì không.",
    "Course terms": "Thuật ngữ môn học",
    "learnability": "khả năng học",
    "feedback": "phản hồi",
    "memory load": "tải nhớ",
    "user control": "quyền kiểm soát",
    "SOURCE · PA2/capture-work/chess/desktop/chess-26-learn-page.png · FIGURE C2-E08 · no participant result claimed": "NGUỒN · PA2/capture-work/chess/desktop/chess-26-learn-page.png · HÌNH C2-E08 · không tuyên bố kết quả người tham gia",
    "Chess · anatomy": "Chess · giải phẫu",
    "13 / 20": "13 / 20",
    "02 · CHESS.COM / ALT 2": "02 · CHESS.COM / PA 2",
    "card review mode": "chế độ review bằng thẻ",
    "CHESS ALTERNATIVE 02": "CHESS · PHƯƠNG ÁN 02",
    "Browse the moments.": "Duyệt các khoảnh khắc.",
    "Choose the lesson.": "Chọn bài học.",
    "Approved artifact · alt2scenario2.png": "Artifact đã duyệt · alt2scenario2.png",
    "recognition": "nhận diện",
    "choice": "lựa chọn",
    "A fixed first step can hide the user’s actual learning priority; a post-game review may contain several moments worth exploring.": "Một bước đầu cố định có thể che mất ưu tiên học thật sự của người dùng; review sau ván có thể có nhiều khoảnh khắc đáng khám phá.",
    "A non-linear dashboard: performance chips → key-moment cards → selected card → explanation → practice action.": "Một dashboard phi tuyến: chip hiệu suất → thẻ khoảnh khắc chính → thẻ được chọn → giải thích → thao tác luyện tập.",
    "Replaces setup-heavy Analysis entry with a recognition-first review overview where the user chooses what to open.": "Thay điểm vào Analysis nặng thiết lập bằng tổng quan review ưu tiên nhận diện, nơi người dùng chọn nội dung muốn mở.",
    "Users can scan the summary, choose a meaningful moment, and reach relevant practice without needing to recall analysis vocabulary.": "Người dùng có thể quét phần tóm tắt, chọn một khoảnh khắc có ý nghĩa và đến bài luyện tập phù hợp mà không cần nhớ từ vựng analysis.",
    "PROTOTYPE · alt2scenario2.png · COMPARISON · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png": "PROTOTYPE · alt2scenario2.png · SO SÁNH · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png",
    "Chess · card review mode": "Chess · chế độ review bằng thẻ",
    "14 / 20": "14 / 20",
    "THE CARD REVIEW MODE IN DETAIL": "CHI TIẾT CHẾ ĐỘ REVIEW BẰNG THẺ",
    "The user controls": "Người dùng kiểm soát",
    "what comes first.": "điều gì đến trước.",
    "01 · key-moment card grid": "01 · lưới thẻ khoảnh khắc chính",
    "02 · selected card + explanation": "02 · thẻ được chọn + giải thích",
    "03 · review / try / puzzle": "03 · review / thử / puzzle",
    "04 · summary chips": "04 · chip tóm tắt",
    "Scanability and recognition: mini-boards, labels, and color-coded moments make comparison visible.": "Khả năng quét và nhận diện: bàn cờ nhỏ, nhãn và khoảnh khắc mã màu làm việc so sánh trở nên rõ ràng.",
    "More visible choices create more decision load. A novice may select a dramatic blunder and skip the most teachable moment.": "Nhiều lựa chọn hiển thị hơn tạo tải quyết định lớn hơn. Người mới có thể chọn một blunder nổi bật và bỏ qua khoảnh khắc dễ học nhất.",
    "Record the first card selected, whether the user can explain why, and whether the practice connection is understood.": "Ghi lại thẻ được chọn đầu tiên, người dùng có giải thích được lý do không, và họ có hiểu mối nối sang luyện tập không.",
    "system-selected order": "thứ tự do hệ thống chọn",
    "user-selected content": "nội dung do người dùng chọn",
    "SOURCE · PA2/evidence-index.csv · C2-E10 + C2-E08 · self-selection is a design hypothesis": "NGUỒN · PA2/evidence-index.csv · C2-E10 + C2-E08 · tự chọn là giả thuyết thiết kế",
    "15 / 20": "15 / 20",
    "02 · CHESS.COM / ALT 3": "02 · CHESS.COM / PA 3",
    "side-by-side assistant": "trợ lý cạnh bàn cờ",
    "CHESS ALTERNATIVE 03": "CHESS · PHƯƠNG ÁN 03",
    "Ask beside the board.": "Hỏi ngay cạnh bàn cờ.",
    "Keep the context.": "Giữ nguyên ngữ cảnh.",
    "Approved artifact · alt3scenario2.png": "Artifact đã duyệt · alt3scenario2.png",
    "context": "ngữ cảnh",
    "conversation": "hội thoại",
    "follow-up": "hỏi tiếp",
    "Beginners need explanations in plain language without leaving the board or knowing which analysis command to choose.": "Người mới cần lời giải thích dễ hiểu mà không phải rời bàn cờ hay biết chọn lệnh analysis nào.",
    "Board + assistant remain visible together: ask → contextual explanation → highlighted square / better move → follow-up.": "Bàn cờ + trợ lý luôn hiển thị cùng nhau: hỏi → giải thích theo ngữ cảnh → ô được đánh dấu / nước đi tốt hơn → hỏi tiếp.",
    "Adds a question-led explanation layer beside the analysis board, while keeping key moments and move context in view.": "Thêm một lớp giải thích dẫn dắt bằng câu hỏi cạnh bàn cờ analysis, đồng thời giữ khoảnh khắc chính và ngữ cảnh nước đi trong tầm nhìn.",
    "Users can ask a natural question, explain the answer in their own words, and continue without losing board context.": "Người dùng có thể hỏi tự nhiên, diễn giải câu trả lời bằng lời của mình và tiếp tục mà không mất ngữ cảnh bàn cờ.",
    "PROTOTYPE · alt3scenario2.png · COMPARISON · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png": "PROTOTYPE · alt3scenario2.png · SO SÁNH · PA2/capture-work/chess/desktop/chess-29-analysis-board.png + chess-26-learn-page.png",
    "Chess · side-by-side assistant": "Chess · trợ lý cạnh bàn cờ",
    "16 / 20": "16 / 20",
    "THE SIDE-BY-SIDE ASSISTANT IN DETAIL": "CHI TIẾT TRỢ LÝ CẠNH BÀN CỜ",
    "the question.": "câu hỏi.",
    "01 · board + key moments": "01 · bàn cờ + khoảnh khắc chính",
    "02 · question + plain answer": "02 · câu hỏi + câu trả lời dễ hiểu",
    "03 · suggested next questions": "03 · câu hỏi tiếp theo gợi ý",
    "04 · contextual board feedback": "04 · phản hồi bàn cờ theo ngữ cảnh",
    "Contextual explanation reduces switching: the board, key moment, response, and next prompt stay in one view.": "Giải thích theo ngữ cảnh giảm việc chuyển đổi: bàn cờ, khoảnh khắc chính, câu trả lời và prompt tiếp theo nằm trong cùng một khung nhìn.",
    "Open-ended answers can be inconsistent or over-trusted. A beginner may not know when the assistant is uncertain.": "Câu trả lời mở có thể không nhất quán hoặc bị tin quá mức. Người mới có thể không biết khi nào trợ lý chưa chắc chắn.",
    "Ask one intentional and one ambiguous follow-up. Observe question formulation, response comprehension, trust calibration, and recovery.": "Đưa ra một câu hỏi tiếp có chủ đích và một câu mơ hồ. Quan sát cách đặt câu hỏi, mức hiểu câu trả lời, hiệu chỉnh niềm tin và khả năng phục hồi.",
    "sequence": "chuỗi",
    "card": "thẻ",
    "question": "câu hỏi",
    "SOURCE · PA2/evidence-index.csv · C2-E10 + C2-E08 · no AI answer quality result claimed": "NGUỒN · PA2/evidence-index.csv · C2-E10 + C2-E08 · không tuyên bố kết quả chất lượng câu trả lời AI",
    "17 / 20": "17 / 20",
    "SCENARIO 02 · COMPARISON": "KỊCH BẢN 02 · SO SÁNH",
    "Same review job.": "Cùng một mục tiêu review.",
    "Different control model.": "Khác mô hình kiểm soát.",
    "Original Chess.com": "Chess.com gốc",
    "Alt 1 · Guided": "PA 1 · Có hướng dẫn",
    "Alt 2 · Cards": "PA 2 · Thẻ",
    "Alt 3 · Assistant": "PA 3 · Trợ lý",
    "Who controls sequence?": "Ai kiểm soát chuỗi?",
    "User chooses among advanced entry paths": "Người dùng chọn giữa các điểm vào nâng cao",
    "System controls order": "Hệ thống kiểm soát thứ tự",
    "User selects a card": "Người dùng chọn một thẻ",
    "User asks a question": "Người dùng đặt câu hỏi",
    "Primary interaction": "Tương tác chính",
    "Setup, explore, search, import, start": "Thiết lập, khám phá, tìm kiếm, import, bắt đầu",
    "Step-by-step review": "Review từng bước",
    "Browse and expand moments": "Duyệt và mở rộng khoảnh khắc",
    "Ask and follow up beside board": "Hỏi và hỏi tiếp cạnh bàn cờ",
    "Beginner guidance": "Hướng dẫn người mới",
    "Low at analysis entry": "Thấp ở điểm vào analysis",
    "High": "Cao",
    "Medium; recognition-led": "Trung bình; dẫn dắt bằng nhận diện",
    "Medium; prompt-dependent": "Trung bình; phụ thuộc prompt",
    "Flexible depth for many users": "Độ sâu linh hoạt cho nhiều người dùng",
    "Learnability and closure": "Khả năng học và hoàn tất",
    "Choice and scanability": "Lựa chọn và khả năng quét",
    "Contextual explanation": "Giải thích theo ngữ cảnh",
    "Recall demand / wrong start": "Gánh nặng nhớ lại / bắt đầu sai",
    "Low flexibility": "Ít linh hoạt",
    "Decision load / skipped priority": "Tải quyết định / bỏ qua ưu tiên",
    "Inconsistent or over-trusted answers": "Câu trả lời không nhất quán hoặc bị tin quá mức",
    "Entry-choice accuracy": "Độ chính xác khi chọn điểm vào",
    "Mistake comprehension": "Hiểu lỗi",
    "Choice rationale + practice": "Lý do chọn + luyện tập",
    "Question quality + trust": "Chất lượng câu hỏi + niềm tin",
    "compare comprehension, control, and practice continuation on the same beginner task before selecting a PA4 direction.": "so sánh mức hiểu, quyền kiểm soát và khả năng tiếp tục luyện tập trên cùng một nhiệm vụ cho người mới trước khi chọn hướng PA4.",
    "SOURCE · PA2/evidence-index.csv · C2-E08 · C2-E10 · PA2/traceability-matrix.csv": "NGUỒN · PA2/evidence-index.csv · C2-E08 · C2-E10 · PA2/traceability-matrix.csv",
    "Chess · comparison": "Chess · so sánh",
    "18 / 20": "18 / 20",
    "PA3 · FORMATIVE TESTING": "PA3 · KIỂM THỬ FORMATIVE",
    "planned measures": "thước đo dự kiến",
    "WHAT THE ALTERNATIVES NEED TO PROVE": "CÁC PHƯƠNG ÁN CẦN CHỨNG MINH ĐIỀU GÌ",
    "Test behavior, not": "Kiểm thử hành vi, không phải",
    "visual polish.": "độ bóng bẩy thị giác.",
    "PA3 requires 2–3 participants with no prior prototype knowledge. The measures below are planned formative checks, not results.": "PA3 cần 2–3 người tham gia chưa biết prototype trước đó. Các thước đo dưới đây là kiểm tra formative dự kiến, không phải kết quả.",
    "FIFA · candidate tasks": "FIFA · nhiệm vụ ứng viên",
    "Can users trust the next action?": "Người dùng có tin thao tác tiếp theo không?",
    "Identify current ticket state. Find what happens next. Find a common ticket action. Judge whether information looks current and official.": "Xác định trạng thái vé hiện tại. Tìm điều xảy ra tiếp theo. Tìm một thao tác vé phổ biến. Đánh giá thông tin có mới và chính thức không.",
    "Observe": "Quan sát",
    "State comprehension · first action · wrong paths · handoff recognition · hesitation · confidence language.": "Hiểu trạng thái · thao tác đầu tiên · đường đi sai · nhận diện chuyển giao · do dự · ngôn ngữ thể hiện sự an tâm.",
    "CHESS · candidate tasks": "CHESS · nhiệm vụ ứng viên",
    "Can beginners turn a mistake into a skill?": "Người mới có biến một lỗi thành kỹ năng không?",
    "Find where to start review. Explain one mistake. Identify and try a better move. Reach relevant practice. Say what they would do next.": "Tìm nơi bắt đầu review. Giải thích một lỗi. Xác định và thử một nước đi tốt hơn. Đến bài luyện tập phù hợp. Nói bước tiếp theo họ sẽ làm gì.",
    "Mistake comprehension · decision load · move trial · practice continuation · perceived control · terminology barriers.": "Hiểu lỗi · tải quyết định · thử nước đi · tiếp tục luyện tập · quyền kiểm soát cảm nhận · rào cản thuật ngữ.",
    "Method boundary": "Ranh giới phương pháp",
    "Keep evidence clean.": "Giữ evidence sạch.",
    "Use neutral scenario prompts, think-aloud, paper-state manipulation, counterbalanced alternative order, and a short post-task interview.": "Dùng prompt kịch bản trung lập, think-aloud, thao tác trạng thái giấy, thứ tự phương án cân bằng và phỏng vấn ngắn sau nhiệm vụ.",
    "Do not claim": "Không tuyên bố",
    "No invented timing targets, preference winners, quotes, or usability scores. Real sessions must be documented separately.": "Không bịa mục tiêu thời gian, phương án được ưa thích, trích dẫn hay điểm usability. Các phiên thực tế phải được ghi nhận riêng.",
    "PA3 success criteria": "Tiêu chí thành công PA3",
    "task completion · own-words comprehension · correct next action · provenance / handoff · move trial / practice · wrong paths · hesitation · perceived control": "hoàn thành nhiệm vụ · hiểu bằng lời của mình · thao tác tiếp theo đúng · nguồn gốc / chuyển giao · thử nước đi / luyện tập · đường đi sai · do dự · quyền kiểm soát cảm nhận",
    "SOURCE · PA3-LKDuy-2026-Public.pdf · pp. 1–3 · PA3/final/Group10-PA3-FormativeTesting.docx · real testing not yet evidenced": "NGUỒN · PA3-LKDuy-2026-Public.pdf · tr. 1–3 · PA3/final/Group10-PA3-FormativeTesting.docx · chưa có evidence kiểm thử thực tế",
    "PA3 · planned measures": "PA3 · thước đo dự kiến",
    "19 / 20": "19 / 20",
    "WHAT PA3 DECIDES FOR PA4": "PA3 QUYẾT ĐỊNH ĐIỀU GÌ CHO PA4",
    "Six distinct interaction hypotheses.": "Sáu giả thuyết tương tác khác biệt.",
    "One evidence-led next step.": "Một bước tiếp theo dẫn dắt bởi evidence.",
    "Formative testing determines which FIFA model builds ticket confidence, which Chess model supports beginner understanding with acceptable decision load, and what advances to hi-fi work.": "Kiểm thử formative xác định mô hình FIFA nào tạo sự an tâm với vé, mô hình Chess nào hỗ trợ người mới hiểu bài với tải quyết định chấp nhận được, và phương án nào được phát triển lên hi-fi.",
    "FIFA · status": "FIFA · trạng thái",
    "FIFA · progress": "FIFA · tiến trình",
    "FIFA · actions": "FIFA · thao tác",
    "Chess · guided": "Chess · có hướng dẫn",
    "Chess · cards": "Chess · thẻ",
    "Chess · conversation": "Chess · hội thoại",
    "PA1 → PA2 → PA3 → PA4": "PA1 → PA2 → PA3 → PA4",
    "End": "Kết thúc",
}

translation_json = repr(translations)
translation_json = translation_json.replace("\\'", "'")
script = f"""
    /* === VIETNAMESE LOCALIZATION === */
    const viTranslations = {translation_json};
    document.documentElement.lang = 'vi';
    document.title = viTranslations['PA3 Paper Prototypes — Group 10'];
    const viTextNodes = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const viNodes = [];
    while (viTextNodes.nextNode()) viNodes.push(viTextNodes.currentNode);
    viNodes.forEach(node => {{
      const key = node.nodeValue.trim();
      if (viTranslations[key]) {{
        const leading = node.nodeValue.match(/^\\s*/)?.[0] || '';
        const trailing = node.nodeValue.match(/\\s*$/)?.[0] || '';
        node.nodeValue = leading + viTranslations[key] + trailing;
      }}
    }});
    document.querySelectorAll('[alt]').forEach(node => {{
      const key = node.getAttribute('alt');
      if (viTranslations[key]) node.setAttribute('alt', viTranslations[key]);
    }});
    document.querySelector('.deck-stage')?.setAttribute('aria-label', 'Bài trình bày prototype giấy PA3');
    const viEdit = document.getElementById('editToggle');
    if (viEdit) {{ viEdit.textContent = '✎ Sửa'; viEdit.title = 'Chế độ sửa (E)'; viEdit.setAttribute('aria-label', 'Bật chế độ sửa'); }}
"""

localized = source.replace('<html lang="en">', '<html lang="vi">', 1)
localized = localized.replace('PA3 Paper Prototypes — Group 10', 'Prototype giấy PA3 — Nhóm 10', 1)
localized = localized.replace('    /* === BOOT === */', script + "\n    /* === BOOT === */", 1)
(ROOT / "index-vi.html").write_text(localized, encoding="utf-8")
print(f"Wrote {ROOT / 'index-vi.html'}")
