flowchart TB
  LM[Le Minh] --> F[FIFA.com] & PR[PeerReview and WeeklyReport] & Q[Final QA]
  NVB[Nguyen Vu Bach] --> F & H[HCI solutions] & Q
  PNGB[Pham Nguyen Gia Bao] --> C[Chess.com] & H & Q
  TMN[Trang Minh Nhut] --> C & H & PR & Q
