import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'GroupID-PA1-Presentation.pptx');
const RENDER = path.join(ROOT, 'output', 'presentation_render_after');
const W=1280,H=720;
const fifa={accent:'#326295',dark:'#102A43',soft:'#EAF3FB'};
const chess={accent:'#769656',dark:'#263A29',soft:'#EEF4E8'};
const img=(...p)=>path.join(ROOT,'assets','presentation','annotated',...p);

const slides=[
{product:'FIFA.com',kind:'Website interactive users',title:'Website interactive users, FIFA.com',image:img('fifa','fifa_home_desktop.png'),
 rows:[['Casual football fan','Xem nhanh tin và trận nổi bật','Mobile, thời gian ngắn','Trang chủ nhiều khối nội dung'],['Tournament follower','Theo lịch và diễn biến giải','Desktop/mobile trong mùa giải','Đường đến Match Centre chưa luôn rõ'],['Media / student researcher','Tìm nguồn chính thức để trích dẫn','Desktop, so sánh nhiều nguồn','Search và nhãn nguồn khó nhận biết']],
 note:'Slide này xác định ba nhóm Website interactive users chính của FIFA.com. Người xem thông thường cần thông tin nhanh, người theo dõi giải cần lịch và diễn biến, còn người làm nội dung cần nguồn chính thức có thể kiểm chứng. Góc nhìn HCI quan trọng vì cùng một trang chủ nhưng mục tiêu, bối cảnh và khó khăn của họ khác nhau. Ảnh chụp cho thấy mật độ nội dung lớn, từ đó dẫn sang các Use Cases cụ thể ở slide tiếp theo.'},
{product:'FIFA.com',kind:'Use Cases',title:'Use Cases, FIFA.com',image:img('fifa','fifa_match_centre_desktop.png'),
 rows:[['Xem lịch trận hôm nay','Cần biết trận sắp diễn ra','Home → Match Centre → ngày','Thấy cặp đấu và thời gian'],['Đọc tin giải đấu','Muốn cập nhật một giải','Home → Tournaments → News','Đọc bài đúng ngữ cảnh giải'],['Kiểm tra nguồn vé chính thức','Chuẩn bị mua vé','Search/menu → ticket page','Nhận diện trang và CTA chính thức'],['Mở FIFA+ xem highlights','Muốn xem lại tình huống','Article/card → FIFA+ → video','Video phát đúng nội dung']],
 note:'Bốn Use Cases này chuyển nhu cầu thành đường tương tác có thể quan sát. Mỗi dòng bắt đầu bằng Trigger, đi qua Interaction path và kết thúc bằng Success outcome. Trong HCI, một tác vụ tốt cần Visibility rõ và Feedback đủ để người dùng biết mình đang đi đúng hướng. Bằng chứng Match Centre minh họa use case có tần suất cao nhất. Sau khi thấy luồng tác vụ, chúng ta đánh giá những điểm FIFA.com đang hỗ trợ tốt.'},
{product:'FIFA.com',kind:'Benefits',title:'Benefits, FIFA.com',image:img('fifa','fifa_tournament_desktop.png'),
 rows:[['Thông tin chính thức','Article + nhãn giải','Recognition over recall','Tin cậy nguồn','Sinh viên trích bài FIFA'],['Match Centre tập trung','Lịch, tỉ số, trạng thái','Visibility + Feedback','Theo dõi nhanh','Fan kiểm tra trận hôm nay'],['Trang giải theo ngữ cảnh','Hero, tab, nội dung liên quan','Information scent','Giảm tìm kiếm lại','Follower ở lại trong giải'],['Responsive đa thiết bị','Menu và layout thích nghi','Consistency','Dùng liên tục','Xem mobile rồi đọc desktop']],
 note:'FIFA.com có bốn Benefits nổi bật khi xét theo nhu cầu người dùng. Nguồn chính thức tạo niềm tin; Match Centre gom trạng thái trận; trang giải giữ đúng ngữ cảnh; và responsive hỗ trợ chuyển thiết bị. Các thành phần UI này giảm việc phải nhớ và tăng Visibility, Feedback cùng Recognition over recall. Ví dụ, người theo dõi giải có thể kiểm tra lịch rồi mở tin liên quan mà không phải dựng lại bối cảnh. Tuy vậy, lợi ích không xóa được các điểm ma sát ở slide Drawbacks.'},
{product:'FIFA.com',kind:'Drawbacks',title:'Drawbacks, FIFA.com',image:img('fifa','fifa_home_mobile.png'),
 rows:[['Điều hướng nhiều tầng','Header + mega menu','Visibility','Chậm đến tác vụ','Cao'],['Trang chủ quá nhiều nội dung','Hero và nhiều feed','Cognitive load','Bỏ sót nội dung cần','Cao'],['Search khó nhận biết','Icon/điểm vào tìm kiếm','Recognition over recall','Tốn thời gian dò','Trung bình'],['Handoff sang FIFA+','Link và ngữ cảnh media','Consistency + Feedback','Cảm giác rời luồng','Trung bình'],['Hiệu năng media','Hero/video dung lượng lớn','Feedback','Chờ tải, rớt tác vụ','Cao']],
 note:'Năm Drawbacks tập trung vào tình huống gây khó khăn chứ không chỉ mô tả giao diện. Điều hướng tầng sâu và trang chủ dày làm tăng Cognitive load; search khó thấy làm giảm Recognition over recall; handoff FIFA+ có thể mất tính liên tục; media nặng làm phản hồi chậm. Mức nghiêm trọng cao dành cho vấn đề trực tiếp cản tác vụ phổ biến hoặc làm người dùng bỏ cuộc. Ảnh mobile cho thấy không gian hạn chế khiến mật độ này rõ hơn. Slide tiếp theo đặt các nhược điểm vào ba tình huống người dùng cụ thể.'},
{product:'FIFA.com',kind:'User difficulty situation',title:'User difficulty situation, FIFA.com',image:img('fifa','fifa_article_desktop.png'),
 rows:[['Casual fan','Mở mobile để xem trận hôm nay','Feed dày, không thấy lối vào lịch','Visibility thấp','Mất thời gian, dễ rời trang'],['Tournament follower','Đi từ bài tin sang highlights','Handoff FIFA+ thiếu liên tục','Feedback / consistency','Không chắc còn trong đúng ngữ cảnh'],['Media researcher','Tìm trang vé hoặc nguồn chính thức','Search và nhãn nguồn khó nhận biết','Recognition over recall','Khó kiểm chứng, phải dò nhiều']],
 note:'Ba tình huống này cho thấy cùng một cấu trúc có thể tạo ra tác động khác nhau theo persona. Casual fan bị chậm vì Visibility thấp, tournament follower mất ngữ cảnh khi sang FIFA+, còn researcher phải nhớ hoặc dò đường đến nguồn chính thức. Đây là các vấn đề HCI có thể thiết kế lại, không phải lỗi năng lực của người dùng. Tác động chung là tăng thời gian, tăng nghi ngờ và tăng khả năng bỏ tác vụ. Vì vậy slide sau đề xuất các sửa đổi trực tiếp trên UI.'},
{product:'FIFA.com',kind:'Recommended solution',title:'Recommended solution, FIFA.com',image:img('fifa','fifa_match_centre_mobile.png'),
 rows:[['Quick task bar','Khó vào lịch/tin/vé/FIFA+','Visibility thấp','4 lối tắt cố định','Đến tác vụ nhanh hơn'],['Search có nhãn','Khó nhận biết tìm kiếm','Recognition kém','Icon + chữ “Tìm kiếm”','Giảm dò menu'],['Context handoff','Mất ngữ cảnh khi sang FIFA+','Feedback thiếu','Banner + breadcrumb nguồn','Biết đang mở nội dung nào'],['Media controls','Tải chậm / tự phát','User control','Poster trước, phát theo chọn','Ổn định và chủ động'],['Progressive home','Trang chủ quá dày','Cognitive load cao','Ưu tiên trận; mở dần feed','Quét nhanh hơn']],
 note:'Mỗi Recommended solution trả lời bốn câu hỏi: sửa vấn đề nào, nguyên nhân HCI là gì, thay đổi UI ra sao và kết quả mong đợi. Quick task bar và search có nhãn tăng Visibility; context handoff giữ Feedback; media controls tăng User control; progressive home giảm Cognitive load. Đây là các thay đổi nhỏ nhưng bám trực tiếp vào use case và bằng chứng đã trình bày. Kết quả cần đo bằng thời gian hoàn thành tác vụ, tỷ lệ tìm đúng và tỷ lệ bỏ trang. Từ đây chúng ta chuyển sang cùng khung phân tích cho Chess.com.'},
{product:'Chess.com',kind:'Website interactive users',title:'Website interactive users, Chess.com',image:img('chess','chess_home_desktop.png'),
 rows:[['Beginner learner','Biết bắt đầu và học nền tảng','Desktop/mobile, phiên ngắn','Quá nhiều lựa chọn Play/Learn/Puzzles'],['Competitive player','Chơi nhanh và cải thiện rating','Desktop, blitz, tập trung cao','Premove và áp lực thời gian'],['Returning player','Ôn lại và hiểu ván cũ','Desktop sau thời gian nghỉ','Game Review nhiều lớp thông tin']],
 note:'Chess.com cũng có ba nhóm Website interactive users nhưng mục tiêu khác FIFA.com. Beginner cần định hướng học, competitive player cần thao tác nhanh và chính xác, returning player cần tái làm quen với phân tích. Giao diện giàu tính năng đem lại giá trị nhưng cũng tạo Cognitive load khác nhau cho từng nhóm. Ảnh trang chủ cho thấy nhiều điểm vào cạnh tranh sự chú ý. Slide sau chuyển các mục tiêu này thành bốn Use Cases.'},
{product:'Chess.com',kind:'Use Cases',title:'Use Cases, Chess.com',image:img('chess','chess_play_desktop.png'),
 rows:[['Chơi rapid game','Muốn bắt đầu ván','Play → time control → Play','Vào bàn đúng thời gian'],['Giải puzzle','Muốn luyện tactic','Puzzles → bài → submit','Nhận đúng/sai và giải thích'],['Mở lesson beginner','Không biết học từ đâu','Learn → Lessons → beginner','Hoàn thành bài theo lộ trình'],['Review game analysis','Vừa kết thúc ván','Game Review → key moves','Hiểu lỗi và bước cải thiện']],
 note:'Bốn Use Cases bao phủ vòng lặp chơi, luyện, học và xem lại. Trigger và Interaction path giúp kiểm tra xem UI có dẫn người dùng đến Success outcome một cách rõ ràng hay không. Bàn cờ là ví dụ mạnh của Direct manipulation vì hành động kéo hoặc chọn quân tạo phản hồi trực tiếp. Puzzle và Game Review bổ sung Feedback sau hành động. Tiếp theo, chúng ta xem các Benefits cụ thể mà hệ sinh thái này tạo ra.'},
{product:'Chess.com',kind:'Benefits',title:'Benefits, Chess.com',image:img('chess','chess_puzzles_clean_desktop.png'),
 rows:[['Bắt đầu ván nhanh','Play + time control','Visibility','Giảm bước','Chọn rapid và ghép trận'],['Bàn cờ trực tiếp','Board + legal moves','Direct manipulation','Thao tác tự nhiên','Kéo quân, thấy nước hợp lệ'],['Game Review phản hồi','Move labels + best move','Feedback','Biết lỗi sau ván','Xem bước ngoặt chính'],['Học theo lộ trình','Puzzles + Study Plans','Progressive disclosure','Tiến bộ có cấu trúc','Beginner học theo cấp']],
 note:'Chess.com hỗ trợ tốt chu trình hành động và học tập. Play flow giảm bước bắt đầu; bàn cờ dùng Direct manipulation; Game Review tạo Feedback; Puzzles và Study Plans tạo lộ trình. Tác động tích cực là người dùng có thể hành động ngay rồi nhận phản hồi để điều chỉnh. Ví dụ, beginner giải puzzle và hiểu ngay nước đi có đúng hay không. Nhưng số lượng tính năng và độ sâu phân tích cũng tạo ra Drawbacks đáng chú ý.'},
{product:'Chess.com',kind:'Drawbacks',title:'Drawbacks, Chess.com',image:img('chess','chess_lessons_clean_desktop.png'),
 rows:[['Nhiều tính năng cho beginner','Nav Play/Learn/Puzzles/Watch','Cognitive load','Không biết bắt đầu','Cao'],['Analysis quá dày','Chart, labels, engine lines','Cognitive load','Khó thấy lỗi chính','Cao'],['Premium gating','Prompt/khóa nội dung','Feedback + continuity','Gián đoạn học','Cao'],['Premove có rủi ro','Queue nước đi','Error prevention','Nước hợp lệ thành yếu','Cao'],['Focus Mode khó tìm','Control ẩn','Visibility','Mất tập trung','Trung bình']],
 note:'Năm Drawbacks này xuất hiện ở các thời điểm nhạy cảm của hành trình. Beginner bị quá tải bởi nhiều lựa chọn; Analysis screen dày; premium gating cắt mạch học; premove thiếu phòng lỗi; Focus Mode khó khám phá. Các vấn đề liên quan trực tiếp đến Cognitive load, Error prevention, Visibility và tính liên tục của Feedback. Mức cao phản ánh nguy cơ làm sai nước hoặc dừng học. Slide tiếp theo cho thấy tác động qua ba tình huống thật cụ thể.'},
{product:'Chess.com',kind:'User difficulty situation',title:'User difficulty situation, Chess.com',image:img('chess','chess_home_mobile.png'),
 rows:[['Beginner','Thấy Play, Learn, Puzzles, Train, Watch','Không biết bắt đầu từ đâu','Cognitive load','Trì hoãn hoặc chọn ngẫu nhiên'],['Competitive player','Dùng premove trong blitz','Phản hồi bất ngờ làm nước chờ trở nên yếu','Error prevention','Mất thế hoặc thua ván'],['Returning player','Mở Game Review sau thời gian nghỉ','Chart, labels, engine lines và access limits','Progressive disclosure','Quá tải, không hiểu lỗi chính']],
 note:'Tình huống thứ nhất là bài toán định hướng: beginner thấy nhiều lựa chọn nhưng không có điểm bắt đầu theo mục tiêu. Tình huống thứ hai là bài toán phòng lỗi: premove hợp lệ ở thời điểm đặt có thể trở thành quyết định yếu sau phản hồi đối thủ. Tình huống thứ ba là bài toán Progressive disclosure khi returning player phải xử lý chart, nhãn nước, engine lines và giới hạn truy cập cùng lúc. Hậu quả trải từ trì hoãn đến thua ván hoặc bỏ phân tích. Slide cuối đề xuất giải pháp theo đúng từng nguyên nhân HCI.'},
{product:'Chess.com',kind:'Recommended solution',title:'Recommended solution, Chess.com',image:img('chess','chess_puzzles_clean_desktop.png'),
 rows:[['Goal-based onboarding','Không biết bắt đầu','Cognitive load','Chọn mục tiêu → lộ trình','Có bước đầu rõ'],['Personal dashboard','Tính năng rời rạc','Visibility','Next action theo mục tiêu','Tiếp tục dễ'],['Beginner analysis preset','Review quá dày','Progressive disclosure','Best move + lỗi chính trước','Hiểu trọng điểm'],['Inline glossary','Không hiểu thuật ngữ','Recognition over recall','Giải thích ngay tại nhãn','Ít rời ngữ cảnh'],['Premove preview + clear','Nước chờ rủi ro','Error prevention','Hiện queue + phím xoá nhanh','Giảm nước ngoài ý muốn'],['Focus Mode coachmark','Khó tìm chế độ tập trung','Visibility','Gợi ý đúng thời điểm','Tập trung nhanh hơn']],
 note:'Bảy ý tưởng được gom thành sáu nhóm UI để giữ slide đọc được: goal-based onboarding, personal dashboard, beginner analysis preset, inline glossary, premove queue preview kết hợp fast clear shortcut, và Focus Mode coachmark. Mỗi nhóm nối rõ vấn đề, nguyên nhân HCI, cách sửa và kết quả mong đợi. Beginner được dẫn theo mục tiêu; returning player thấy lớp phân tích đơn giản trước; competitive player nhìn và xoá premove nhanh; mọi người dễ khám phá Focus Mode hơn. Các giải pháp ưu tiên Progressive disclosure, Error prevention, Visibility và Recognition over recall. Đây là điểm kết thúc của phần Chess.com và cũng là bộ đề xuất có thể đưa vào prototype kiểm thử.'}
];

function box(slide,x,y,w,h,fill='#FFFFFF',stroke='#D8E0E8',radius='rounded-xl'){
 return slide.shapes.add({geometry:'roundRect',position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:stroke,width:1},borderRadius:radius});
}
function text(slide,s,x,y,w,h,size=18,color='#102A43',bold=false,align='left'){
 const t=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}}); t.text=s; t.text.style={fontFamily:'Aptos',fontSize:size,color,bold,alignment:align,verticalAlignment:'middle'}; return t;
}
async function addImage(slide,p,x,y,w,h){const b=await fs.readFile(p); slide.images.add({blob:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),contentType:'image/png',alt:path.basename(p),fit:'contain',position:{left:x,top:y,width:w,height:h},geometry:'roundRect',borderRadius:'rounded-xl'});}
function header(slide,d,i,pal){text(slide,d.kind.toUpperCase(),64,24,700,24,14,pal.accent,true);text(slide,d.title,64,54,1080,54,36,pal.dark,true);text(slide,String(i+1).padStart(2,'0'),1160,28,56,28,16,pal.accent,true,'right');const l=slide.shapes.add({geometry:'rect',position:{left:64,top:118,width:92,height:4},fill:pal.accent,line:{style:'solid',fill:pal.accent,width:0}});text(slide,`HCI • PA1 • ${d.product}`,64,690,420,16,11,'#64748B');text(slide,`${i+1} / 12`,1120,690,96,16,11,'#64748B',false,'right');}
function cellText(parts,widths){return parts.map((v,i)=>({v,w:widths[i]}));}
async function build(){await fs.mkdir(RENDER,{recursive:true});const p=Presentation.create({slideSize:{width:W,height:H}});
 for(let i=0;i<slides.length;i++){const d=slides[i],pal=d.product==='FIFA.com'?fifa:chess,s=p.slides.add();s.background.fill='#F7F9FC';header(s,d,i,pal);
  const isSolution=d.kind==='Recommended solution', isTable=['Benefits','Drawbacks','User difficulty situation','Use Cases','Recommended solution'].includes(d.kind);
  if(!isTable){await addImage(s,d.image,830,154,386,458);const labels=['Nhóm user','Mục tiêu','Bối cảnh','Khó khăn chính'];const widths=[200,250,250,500];text(s,labels.join('   •   '),64,146,730,28,14,pal.accent,true);let y=188;for(const r of d.rows){box(s,64,y,730,126,'#FFFFFF');text(s,r[0],82,y+10,180,28,18,pal.dark,true);text(s,'Mục tiêu',278,y+10,90,22,12,pal.accent,true);text(s,r[1],278,y+34,220,66,15,pal.dark);text(s,'Bối cảnh',512,y+10,90,22,12,pal.accent,true);text(s,r[2],512,y+34,118,66,14,pal.dark);text(s,'Khó khăn',644,y+10,100,22,12,pal.accent,true);text(s,r[3],644,y+34,132,70,14,pal.dark);y+=140;}}
  else {await addImage(s,d.image,944,154,272,150);let headers;if(d.kind==='Use Cases')headers=['Use case','Trigger','Interaction path','Success outcome'];else if(d.kind==='Benefits')headers=['Benefit','UI liên quan','HCI concept','Tác động','Ví dụ'];else if(d.kind==='Drawbacks')headers=['Khó khăn','UI liên quan','HCI bị ảnh hưởng','Hậu quả','Mức độ'];else if(d.kind==='User difficulty situation')headers=['Persona','Context','Problem','HCI cause','Impact'];else headers=['Solution','Khắc phục','Nguyên nhân HCI','Cách sửa trên UI','Kết quả'];
   const left=64,top=154,total=848,rowH=isSolution?65:(d.rows.length===5?76:91),colW=headers.length===4?[180,210,260,198]:[165,175,170,175,163];box(s,left,top,total,40,pal.dark,pal.dark);let x=left;headers.forEach((h,j)=>{text(s,h,x+8,top+4,colW[j]-16,32,13,'#FFFFFF',true);x+=colW[j];});let y=top+46;for(let ri=0;ri<d.rows.length;ri++){const r=d.rows[ri];box(s,left,y,total,rowH-6,ri%2?pal.soft:'#FFFFFF',pal.soft);x=left;for(let j=0;j<r.length;j++){text(s,r[j],x+8,y+5,colW[j]-16,rowH-16,isSolution?12.5:13.5,j===0?pal.dark:'#334155',j===0);x+=colW[j];}y+=rowH;}}
  s.speakerNotes.textFrame.setText(d.note);s.speakerNotes.setVisible(true);
  const png=await p.export({slide:s,format:'png',scale:1});await fs.writeFile(path.join(RENDER,`slide_${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await png.arrayBuffer()));
 }
 const pptx=await PresentationFile.exportPptx(p);await pptx.save(OUT);await fs.mkdir(path.join(ROOT,'output'),{recursive:true});await fs.copyFile(OUT,path.join(ROOT,'output','GroupID-PA1-Presentation.pptx'));
 const inspect=await p.inspect({kind:'slide,textbox,image,notes',maxChars:200000});await fs.writeFile(path.join(ROOT,'GroupID-PA1-Presentation.pptx.inspect.ndjson'),inspect.ndjson,'utf8');
 const script=['# Kịch bản thuyết trình PA1 — FIFA.com và Chess.com',''];slides.forEach((d,i)=>{script.push(`## Slide ${i+1}. ${d.title}`,'',d.note,'',`Chuyển ý: ${i===slides.length-1?'Đây là phần kết thúc của bài trình bày.':`Tiếp theo, chúng ta xem ${slides[i+1].title}.`}`,'');});await fs.mkdir(path.join(ROOT,'scripts'),{recursive:true});await fs.writeFile(path.join(ROOT,'scripts','presentation_script_vi.md'),script.join('\n'),'utf8');
}
build().catch(e=>{console.error(e);process.exitCode=1});
